baseURL = "https://ucstr.org/"
languageCode = "en-us"
title = "UCSTR"
theme = "congo"

paginate = 10
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menu.main]]
    name = "Research culture"
    pageRef = "categories/research"
    weight = 2
  [[menu.main]]
    name = "Policy watch"
    pageRef = "categories/policy"
    weight = 3
  [[menu.main]]
    name = "Voices"
    pageRef = "categories/voices"
    weight = 4
  [[menu.main]]
    name = "Resources"
    pageRef = "categories/resources"
    weight = 5
  [[menu.main]]
    name = "About"
    pageRef = "about"
    weight = 6

    [params.footer]
  showThemeAttribution = false